# Generated by Django 3.2.15 on 2022-08-09 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_room_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='gender',
        ),
    ]
