# Generated by Django 3.2.15 on 2022-08-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_remove_hostel_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=None, max_length=100)),
                ('room_type', models.CharField(choices=[('S', 'Single Occupancy'), ('F', 'With fridge'), ('FT', 'with fridge and TV')], default='D', max_length=10000)),
            ],
        ),
        migrations.AddField(
            model_name='hostel',
            name='building',
            field=models.ManyToManyField(blank=True, default=None, to='room.Building'),
        ),
    ]
